---
services:
  grafana:
    command:
    - -config=/etc/grafana/grafana.ini
    container_name: grafana
    image: index.docker.io/utxobr/monero-exporter-grafana@sha256:0e9f595487e7ee07f9059f75c302ce56fbe559074c0ba95a1d46a9a3c1c859a2
    ports:
    - 3000:3000
    volumes:
    - ./grafana/grafana.ini:/etc/grafana/grafana.ini:ro
    - ./grafana/provisioning:/etc/grafana/provisioning:ro
    - ./grafana/dashboards:/var/lib/grafana/dashboards:ro
  monero-exporter:
    command:
    - --monero-addr=http://127.0.0.1:18081
    container_name: monero-exporter
    image: index.docker.io/utxobr/monero-exporter@sha256:737413b1054583535e835e1417b61a8d59a4c08723e4a15c61c4249c2a7d69a4
    network_mode: service:monerod
  monerod:
    command:
    - --check-updates=disabled
    - --data-dir=/data
    - --enforce-dns-checkpointing
    - --in-peers=2048
    - --limit-rate=999999
    - --no-igd
    - --no-zmq
    - --out-peers=64
    - --p2p-bind-ip=0.0.0.0
    - --p2p-bind-port=18080
    - --public-node
    - --rpc-bind-ip=127.0.0.1
    - --rpc-bind-port=18081
    - --rpc-restricted-bind-ip=0.0.0.0
    - --rpc-restricted-bind-port=18089
    container_name: monerod
    image: index.docker.io/utxobr/monero-exporter-monerod@sha256:15a70938c401a744b34d278fa345fb2e66fae8b428929ae52f1cea455e5bfcd9
    ports:
    - 18080:18080
    - 18089:18089
    volumes:
    - monerod-data:/data
  prometheus:
    command:
    - --config.file=/etc/prometheus/config.yaml
    - --storage.tsdb.path=/data
    - --storage.tsdb.retention.time=180d
    container_name: prometheus
    image: index.docker.io/utxobr/monero-exporter-prometheus@sha256:21fcd719c6a3c8de35d513887e6666a5c49a15be742e328c034511cd60b5573e
    volumes:
    - prometheus-data:/data
    - ./prometheus/config.yaml:/etc/prometheus/config.yaml:ro
version: "3"
volumes:
  monerod-data: null
  prometheus-data: null
