{
 "title": "Monero",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "quantile",
    "label": "quantile",
    "query": {
     "query": "label_values(monero_lastblock_transactions_inputs,quantile)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Main network",
   "type": "stat",
   "description": "Whether the node is running against mainnet or not.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monero_info_mainnet", "legendFormat": "mainnet" }
   ]
  },
  {
   "title": "Synchronized",
   "type": "stat",
   "description": "Whether the node is fully in sync with the network or not.",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "monero_info_synchronized", "legendFormat": "mainnet" }
   ]
  },
  {
   "title": "Overall",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "Height and Target",
     "type": "timeseries",
     "description": "Current chain's block height vs node's current height. When syncing, let's one quickly tell how far the node is from being synchronized with the network.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "monero_info_height", "legendFormat": "height" },
      { "expr": "monero_info_target_height", "legendFormat": "target" }
     ]
    },
    {
     "title": "Block size median and limit",
     "type": "timeseries",
     "description": "Maximum hard limit for block size scaling, as well as median used for scaling factor",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "monero_info_block_size_limit", "legendFormat": "limit" },
      { "expr": "monero_info_block_size_median", "legendFormat": "median" }
     ]
    },
    {
     "title": "Uptime",
     "type": "timeseries",
     "description": "For how long this node has been up.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 3 },
     "fieldConfig": { "defaults": { "unit": "dtdhms" } },
     "targets": [
      {
       "expr": "monero_info_uptime_seconds_total",
       "legendFormat": "limit"
      }
     ]
    },
    {
     "title": "Alternative blocks",
     "type": "timeseries",
     "description": "Number of blocks alternative to the longest chain",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 10 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "monero_info_alternative_blocks", "legendFormat": "alternative blocks" }
     ]
    }
   ]
  },
  {
   "title": "Networking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "White Peerlist last seen distribution",
     "type": "timeseries",
     "description": "The distribution of how long ago peers in the whitelist have been seen.\n",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "monero_peerlist_lastseen{quantile=~\"$quantile\"}",
       "legendFormat": "{{ quantile }}"
      }
     ]
    },
    {
     "title": "Peerlists' count",
     "type": "timeseries",
     "description": "Number of peers in each peer list.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "monero_peerlist", "legendFormat": "{{ type }}" }
     ]
    },
    {
     "title": "Data rate",
     "type": "timeseries",
     "description": "Rate of data transmission in and out from this node (p2p and rpc).",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 4 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      { "expr": "rate(monero_net_rx_bytes[1m])", "legendFormat": "rx" },
      { "expr": "rate(monero_net_tx_bytes[1m])", "legendFormat": "tx" }
     ]
    },
    {
     "title": "Connections by direction (in/out)",
     "type": "timeseries",
     "description": "Number of connections based on their direction (incoming/outgoing)",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(monero_p2p_connections) by (type)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Connections by connection state",
     "type": "timeseries",
     "description": "Number of connections based on their connection state.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "sum(monero_p2p_connections) by (state)",
       "legendFormat": "{{ type }}"
      }
     ]
    },
    {
     "title": "Data",
     "type": "timeseries",
     "description": "Total amount of data sent and received by this node.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 11 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "monero_net_rx_bytes", "legendFormat": "rx" },
      { "expr": "monero_net_tx_bytes", "legendFormat": "tx" }
     ]
    },
    {
     "title": "P2P Peers Data Receive Rate",
     "type": "timeseries",
     "description": "The distribution of data retrieval from our connected peers.\n",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "monero_p2p_connections_rx_rate_bps{quantile=~\"$quantile\"}",
       "legendFormat": "{{ quantile }}"
      }
     ]
    },
    {
     "title": "P2P Peers Data Transmission Rate",
     "type": "timeseries",
     "description": "The distribution of data transmission to our connected peers.\n",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "expr": "monero_p2p_connections_tx_rate_bps{quantile=~\"$quantile\"}",
       "legendFormat": "{{ quantile }}"
      }
     ]
    },
    {
     "title": "Connected Peers' Height",
     "type": "timeseries",
     "description": "The distribution of the heights of our peers\n",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "monero_p2p_connections_height{quantile=~\"$quantile\"}",
       "legendFormat": "{{ quantile }}"
      }
     ]
    },
    {
     "title": "Connections' Age",
     "type": "timeseries",
     "description": "The distribution of the age of the connections established to/from our nodes.\n",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 25 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "monero_p2p_connections_age{quantile=~\"$quantile\"}",
       "legendFormat": "{{ quantile }}"
      }
     ]
    }
   ]
  },
  {
   "title": "RPC",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "RPC hits per minute",
     "type": "timeseries",
     "description": "Average number of RPC requests served over the past minute.\n\nps.: this includes the calls made by the stats collector too.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "increase(monero_rpc_hits_total[1m])",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "Time spent serving RPC methods",
     "type": "timeseries",
     "description": "Average amount of time spent serving RPC methods over that past minute.\n\nps.: this includes the calls made by the stats collector too.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 5 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "rate(monero_rpc_seconds_total[1m])",
       "legendFormat": "{{method}}"
      }
     ]
    },
    {
     "title": "RPC Connections",
     "type": "timeseries",
     "description": "Number of RPC connections being served.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "monero_info_rpc_connections", "legendFormat": "connections" }
     ]
    }
   ]
  },
  {
   "title": "Transaction Pool",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "Spent Key Images",
     "type": "timeseries",
     "description": "Total number of key images spent across all transactions that are still in the pool",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "monero_transaction_pool_spent_key_images",
       "legendFormat": "spent key images"
      }
     ]
    },
    {
     "title": "Size",
     "type": "timeseries",
     "description": "Total size of the block",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "monero_transaction_pool_size_bytes",
       "legendFormat": "size"
      }
     ]
    },
    {
     "title": "Transactions",
     "type": "timeseries",
     "description": "Number of transactions in the transaction pool.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 6 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "monero_transaction_pool_transactions",
       "legendFormat": "fee"
      }
     ]
    },
    {
     "title": "Transaction Size",
     "type": "timeseries",
     "description": "The distribution of the sizes of the transactions in the pool.\n",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "monero_transaction_pool_transactions_size_bytes{quantile=~\"$quantile\"}",
       "legendFormat": "{{ quantile }}"
      }
     ]
    },
    {
     "title": "Transaction Fees Distribution (per kB)",
     "type": "timeseries",
     "description": "The distribution fees (in micronero) per kB for the transactions still in the transaction pool.\n",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "µɱ" } },
     "targets": [
      {
       "expr": "monero_transaction_pool_fees_micronero_per_kb{quantile=~\"$quantile\"}",
       "legendFormat": "{{ quantile }}"
      }
     ]
    },
    {
     "title": "Fees",
     "type": "timeseries",
     "description": "Total amount of fees (in Monero) for the transactions in the transaction pool.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
     "fieldConfig": { "defaults": { "unit": "ɱ" } },
     "targets": [
      {
       "expr": "monero_transaction_pool_fees_monero",
       "legendFormat": "fee"
      }
     ]
    },
    {
     "title": "Transaction Inputs",
     "type": "timeseries",
     "description": "The distribution of the amount of inputs used in transactions still in the transaction pool. \n",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 20 },
     "targets": [
      {
       "expr": "monero_transaction_pool_transactions_inputs{quantile=~\"$quantile\"}",
       "legendFormat": "{{ quantile }}"
      }
     ]
    },
    {
     "title": "Transaction Outputs",
     "type": "timeseries",
     "description": "The distribution of the amount of outputs used in transactions still in the transaction pool. \n",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 20 },
     "targets": [
      {
       "expr": "monero_transaction_pool_transactions_outputs{quantile=~\"$quantile\"}",
       "legendFormat": "{{ quantile }}"
      }
     ]
    },
    {
     "title": "Inputs and Outputs",
     "type": "timeseries",
     "description": "Total number of inputs and outputs from the transactions still in the pool.",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "monero_transaction_pool_transactions_inputs_sum",
       "legendFormat": "inputs"
      },
      {
       "expr": "monero_transaction_pool_transactions_outputs_sum",
       "legendFormat": "outputs"
      }
     ]
    },
    {
     "title": "Weird cases",
     "type": "timeseries",
     "description": "A couple of statistics that reveals weird scenarios found in the transaction pool.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "monero_transaction_pool_double_spends",
       "legendFormat": "double spends"
      },
      {
       "expr": "monero_transaction_pool_older_than_10m",
       "legendFormat": "older than 10m"
      },
      {
       "expr": "monero_transaction_pool_failing_transactions",
       "legendFormat": "failing transactions"
      },
      {
       "expr": "monero_transaction_pool_not_relayed",
       "legendFormat": "not relayed"
      }
     ]
    },
    {
     "title": "Transaction Age",
     "type": "timeseries",
     "description": "Distribution of for how long transactions have been sitting in the pool.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "monero_transaction_pool_transactions_age{quantile=~\"$quantile\"}",
       "legendFormat": "{{ quantile }}"
      }
     ]
    }
   ]
  },
  {
   "title": "Last Block",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "Height",
     "type": "timeseries",
     "description": "Height of the last block in the chain.",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      { "expr": "monero_lastblock_height", "legendFormat": "transactions" }
     ]
    },
    {
     "title": "Fees",
     "type": "timeseries",
     "description": "Total amount of fees (in Monero) included in the last block.",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ɱ" } },
     "targets": [
      { "expr": "monero_lastblock_fees_monero", "legendFormat": "fee" }
     ]
    },
    {
     "title": "Subsidy",
     "type": "timeseries",
     "description": "Newly amount of Monero created in this block as a miner subsidy. ",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 7 },
     "fieldConfig": { "defaults": { "unit": "ɱ" } },
     "targets": [
      {
       "expr": "monero_lastblock_subsidy_monero",
       "legendFormat": "block subsidy"
      }
     ]
    },
    {
     "title": "Transaction Fees Distribution (per kB)",
     "type": "timeseries",
     "description": "The distribution fees (in micronero) per kB for the transactions included in the block seen as last at the time.\n",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "µɱ" } },
     "targets": [
      {
       "expr": "monero_lastblock_fees_micronero_per_kb{quantile=~\"$quantile\"}",
       "legendFormat": "{{ quantile }}"
      }
     ]
    },
    {
     "title": "Rewards",
     "type": "timeseries",
     "description": "Total block rewards granted to the miner of this block (transaction fees + block subsidy).",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "ɱ" } },
     "targets": [
      { "expr": "monero_lastblock_reward_monero", "legendFormat": "total rewards" }
     ]
    },
    {
     "title": "Size",
     "type": "timeseries",
     "description": "Total size of the block",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 14 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      { "expr": "monero_lastblock_size_bytes", "legendFormat": "size" }
     ]
    },
    {
     "title": "Transactions",
     "type": "timeseries",
     "description": "Number of transactions included in the block",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      { "expr": "monero_lastblock_transactions", "legendFormat": "transactions" }
     ]
    },
    {
     "title": "Inputs and Outputs",
     "type": "timeseries",
     "description": "Number of transactions included in the block",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "short" } },
     "targets": [
      {
       "expr": "monero_lastblock_transactions_inputs_sum",
       "legendFormat": "inputs"
      },
      {
       "expr": "monero_lastblock_transactions_outputs_sum",
       "legendFormat": "outputs"
      }
     ]
    },
    {
     "title": "Transaction Size Distribution",
     "type": "timeseries",
     "description": "The distribution of sizes of the transactions included in this block.\n",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 21 },
     "fieldConfig": { "defaults": { "unit": "decbytes" } },
     "targets": [
      {
       "expr": "monero_lastblock_transactions_size_bytes{quantile=~\"$quantile\"}",
       "legendFormat": "{{ quantile }}"
      }
     ]
    },
    {
     "title": "Transaction Inputs",
     "type": "timeseries",
     "description": "The distribution of the amount of inputs used in transactions included in this block. \n",
     "gridPos": { "h": 7, "w": 8, "x": 0, "y": 28 },
     "targets": [
      {
       "expr": "monero_lastblock_transactions_inputs{quantile=~\"$quantile\"}",
       "legendFormat": "{{ quantile }}"
      }
     ]
    },
    {
     "title": "Transaction Outputs",
     "type": "timeseries",
     "description": "The distribution of the amount of outputs used in transactions included in this block. \n",
     "gridPos": { "h": 7, "w": 8, "x": 8, "y": 28 },
     "targets": [
      {
       "expr": "monero_lastblock_transactions_outputs{quantile=~\"$quantile\"}",
       "legendFormat": "{{ quantile }}"
      }
     ]
    },
    {
     "title": "Difficulty",
     "type": "timeseries",
     "description": "Difficulty used for mining the last block",
     "gridPos": { "h": 7, "w": 8, "x": 16, "y": 28 },
     "fieldConfig": { "defaults": { "unit": "sci" } },
     "targets": [
      { "expr": "monero_lastblock_difficulty", "legendFormat": "size" }
     ]
    }
   ]
  }
 ]
}